%1000000001000000 CONSTANT VGA_VIA
VGA_VIA 1+ CONSTANT VGA_DATA
VGA_VIA 3 + CONSTANT VGA_DATA_DIR
VGA_VIA $A + CONSTANT VGA_SHIFT_REG
VGA_VIA $B + CONSTANT VGA_ACR
VGA_VIA $C + CONSTANT VGA_PCR

: VGA_INIT
  $FF VGA_DATA_DIR C!
  %1010 VGA_PCR C!
  %11000 VGA_ACR C!
;

: VGA_WRITE ( C ADDR -- ) 
    DUP 8 >> VGA_SHIFT_REG C!
    $FF AND VGA_SHIFT_REG C!
    VGA_DATA C!
;

: XY_VGA_WRITE ( C X Y -- )
   64 * + VGA_WRITE
;

: TO_VGA ( c -- )
   %1100 VGA_PCR C!
   VGA_DATA C!
;

: VGA_FILL ( C -- )
   240 0 DO
      40 0 DO
         DUP I J XY_VGA_WRITE
      LOOP
   LOOP

   DROP
;

\ 0 .. 39
\ 64 in the line
\ 240 lines
