UART_ADDR = %1000000000100000
UART_DATA_REG = UART_ADDR
UART_STATUS_REG = UART_ADDR + 1
UART_COMMAND_REG = UART_ADDR + 2
UART_CONTROL_REG = UART_ADDR + 3

UART_STATUS_INTERRUPT = $80
UART_STATUS_DATA_SET_READY = $40
UART_STATUS_DATA_CARRIER_DETECT = $20
UART_STATUS_TRANSMITTER_DATA_REGISTER_EMPTY = $10
UART_STATUS_RECEIVER_DATA_REGISTER_FULL = $08
UART_STATUS_OVERRUN = $04
UART_STATUS_FRAMING_ERROR = $02
UART_STATUS_PARITY_ERROR = $01

; 1 stop bit & parity, 8 bits word length, internal baud rate, 9600
UART_CONTROL_DEFAULT = %10011110

UART_COMMAND_RECEIVER_ODD_PARITY_CHECKED = $00
UART_COMMAND_RECEIVER_EVEN_PARITY_CHECKED = $40
UART_COMMAND_RECEIVER_PARITY_CHECK_DISABLED = $C0
UART_COMMAND_PARITY_MOD_ENABLED = $20
UART_COMMAND_PARITY_MOD_DISABLED = $0
UART_COMMAND_RECEIVER_NOMRAL_MOD = $0
UART_COMMAND_RECEIVER_ECHO_MOD = $10
UART_COMMAND_TRANSMIT_INTERRUPT_DISABLED_FOR_ECHO = 0
UART_COMMAND_TRANSMIT_INTERRUPT_ENABLED = $04
UART_COMMAND_TRANSMIT_INTERRUPT_DISABLED = $08
UART_COMMAND_TRANSMIT_INTERRUPT_DISABLED_BREAK_ON_TXD = $0C
UART_COMMAND_RECEIVER_INTERRUPT_REQUEST_ENABLED = 0
UART_COMMAND_RECEIVER_INTERRUPT_REQUEST_DISABLED = $02
UART_COMMAND_DATA_TERMINAL_READY = $01
UART_COMMAND_DATA_TERMINAL_NOT_READY = 0
