    INCLUDE "../std/std.asm"
    INCLUDE "display.asm"

    SEG code

FIRST_STR: STRING "FIRST"
SECOND_STR: STRING "SECOND"
THIRD_STR: STRING "THIRD"
FOURTH_STR: STRING "FOURTH"

main:
; Disable all interrupts
    LDA #$7F
    STA VIA_FIRST_IER
    STA VIA_SECOND_IER

; Setup handshakes
    LDA #%11001100
    STA VIA_FIRST_PCR
    STA VIA_SECOND_PCR

; Init display 
    WRITE_WORD VIA_FIRST_PCR, DISPLAY_PCR
    WRITE_WORD VIA_FIRST_RB, DISPLAY_ADDR
    WRITE_WORD VIA_FIRST_DDRB, DISPLAY_DDR
    LDA #%00100000
    STA DISPLAY_PCR_MASK
    JSR INIT_DISPLAY

    WRITE_WORD VIA_FIRST_PCR, DISPLAY_PCR
    WRITE_WORD VIA_FIRST_RA, DISPLAY_ADDR
    WRITE_WORD VIA_FIRST_DDRA, DISPLAY_DDR
    LDA #%00000010
    STA DISPLAY_PCR_MASK
    JSR INIT_DISPLAY

    WRITE_WORD VIA_SECOND_PCR, DISPLAY_PCR
    WRITE_WORD VIA_SECOND_RB, DISPLAY_ADDR
    WRITE_WORD VIA_SECOND_DDRB, DISPLAY_DDR
    LDA #%00100000
    STA DISPLAY_PCR_MASK
    JSR INIT_DISPLAY

    WRITE_WORD VIA_SECOND_PCR, DISPLAY_PCR
    WRITE_WORD VIA_SECOND_RA, DISPLAY_ADDR
    WRITE_WORD VIA_SECOND_DDRA, DISPLAY_DDR
    LDA #%00000010
    STA DISPLAY_PCR_MASK
    JSR INIT_DISPLAY



    WRITE_WORD VIA_FIRST_PCR, DISPLAY_PCR
    WRITE_WORD VIA_FIRST_RB, DISPLAY_ADDR
    WRITE_WORD VIA_FIRST_DDRB, DISPLAY_DDR
    LDA #%00100000
    STA DISPLAY_PCR_MASK
    WRITE_WORD FIRST_STR, DISPLAY_STRING_ADDR
    JSR PRINT_STRING   


    WRITE_WORD VIA_FIRST_PCR, DISPLAY_PCR
    WRITE_WORD VIA_FIRST_RA, DISPLAY_ADDR
    WRITE_WORD VIA_FIRST_DDRA, DISPLAY_DDR
    LDA #%00000010
    STA DISPLAY_PCR_MASK
    WRITE_WORD SECOND_STR, DISPLAY_STRING_ADDR
    JSR PRINT_STRING   
    
    WRITE_WORD VIA_SECOND_PCR, DISPLAY_PCR
    WRITE_WORD VIA_SECOND_RB, DISPLAY_ADDR
    WRITE_WORD VIA_SECOND_DDRB, DISPLAY_DDR
    LDA #%00100000
    STA DISPLAY_PCR_MASK
    WRITE_WORD THIRD_STR, DISPLAY_STRING_ADDR
    JSR PRINT_STRING   


    WRITE_WORD VIA_SECOND_PCR, DISPLAY_PCR
    WRITE_WORD VIA_SECOND_RA, DISPLAY_ADDR
    WRITE_WORD VIA_SECOND_DDRA, DISPLAY_DDR
    LDA #%00000010
    STA DISPLAY_PCR_MASK
    WRITE_WORD FOURTH_STR, DISPLAY_STRING_ADDR
    JSR PRINT_STRING   

    ; JSR CLEAR_DISPLAY
    
    ; LDA #"!"
    ; JSR PRINT_CHAR

    ; LDA #"3"
    ; JSR PRINT_CHAR

    RTS
    